name: AR Manual Server

on:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ENV: ${{secrets.ENV}}
      PORT: ${{secrets.PORT}}
      JWT_SECRET: ${{secrets.JWT_SECRET}}
      # TypeORM
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: localhost
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: project_db
      TYPEORM_SYNCHRONIZE: false
      TYPEORM_ENTITIES: src/entities/**/*.ts,build/entities/**/*.js
      TYPEORM_ENTITIES_DIR: src/entities/generated
      TYPEORM_MIGRATIONS: config/migrations/**/*.ts,config/migrations/**/*.js
      TYPEORM_MIGRATIONS_DIR: config/migrations~
      # Google Cloud
      GOOGLE_CLOUD_PROJECT: ${{secrets.GOOGLE_CLOUD_PROJECT}}
      GOOGLE_CLOUD_CREDENTIALS: ${{secrets.GOOGLE_CLOUD_CREDENTIALS}}
      GOOGLE_CLOUD_BUCKET_NAME: ${{secrets.GOOGLE_CLOUD_BUCKET_NAME}}
      GOOGLE_CLOUD_KEYFILE: ${{secrets.GOOGLE_CLOUD_KEYFILE}}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Environment
        run: touch .env

      - name: Setup Docker
        working-directory: .
        run: docker-compose up -d

      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies And Run
        run: |
          yarn
          yarn typeorm:prod migration:run
          yarn test:coverage
